POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "user1",
    "password": "password1"
}
###

GET http://localhost:8080/systemInfo

###

DELETE  http://localhost:8080/users?id=asd23234
Authorization: mf9oxjfeugb

###
GET http://localhost:8080/users?id=6eVMjt5MjH3PbXYA
Authorization: vjwe9cgpn9n

###

GET http://localhost:8080/users?name=user1
Authorization: 7kosazp0q4n

###
PUT http://localhost:8080/users
Authorization: 7kosazp0q4n
Content-Type: application/json

{
  "age": 21,
  "email": "some@otheremail.com",
  "name": "boo",
  "workingPosition": 3
}